- name: Create ansible user
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Create Ansible user
      user:
        name: "{{ new_ansible_user }}"
        password: "{{ new_ansible_password | password_hash('sha512') }}"
        update_password: always
        
    - name: Add public key to authorized_keys
      authorized_key:
        user: "{{ new_ansible_user }}"
        key: "{{ lookup('file', '../id_rsa.pub') }}"
        exclusive: yes
    
    - name: Add Ansible user to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: "{{ new_ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: visudo -cf %s
        state: present