vps:
  hosts:
    vps01:
      ansible_host: 192.168.56.10
    vps02:
      ansible_host: 192.168.56.11
  vars:
    ansible_user: vagrant
    new_ansible_user: ansible
    new_ansible_password: ansible
network:
  children:
    vps:
