vps:
  hosts:
    vps01:
      ansible_host: 192.168.56.10
    vps02:
      ansible_host: 192.168.56.11
  vars:
    ansible_user: ansible
    ansible_ssh_pass: ansible123
    ansible_sudo_pass: ansible123
network:
  children:
    vps:
