vps:
  hosts:
    vps01:
      ansible_host: 192.168.56.11
  vars:
    ansible_user: ansible
    ansible_ssh_pass: ansible123
    ansible_sudo_pass: ansible123
    gitlabuser: git-user
    gitlabpassword: git-access-token-or-password
    gitlabprotocol: http
    gitlabinstance: git-instance
    projectname: project-name
    projectlocation: project-location-on-remote-host
    servicename: systemd-service-name
    gitlabrepo: user-or-group/repo.git
    requirementfile: python-requirements-file
    ansible_connection: ssh
    ansible_ssh_private_key_file: "{{inventory_dir}}/../../id_rsa"
network:
  children:
    vps: